---

port: 4000
host: 0.0.0.0
safe: false

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /blog/:year/:title/  # Set permalink structure for blog posts
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge
future: true
baseurl: "/blog"  # Blog content is served from the /blog subdirectory

### content configuration ###
title:       "Timmy Reilly's Backup Blog"
keywords:    "Timmy Reilly, Engineering"
description: "A place to learn!"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "blog/img/favicon.ico"
touch_icon:  "blog/img/apple-touch-icon.png"
google_analytics_key: UA-49607422-1  ## Add your Google Analytics key here

### template colors, used site-wide via CSS ###
colors:
  black:     '#000000'
  white:     '#ffffff'
  lightgray: '#D2D2D2'
  darkgray:  '#505050'
  blue:      '#0078D7'
  green:     '#107C10'
  purple:    '#5C2D91'
  turquoise: '#0fbfcf'
  yellow:    '#FFB900'
  orange:    '#D83B01'
  red:       '#E81123'
  magenta:   '#E40098'
  teal:      '#008272'

kramdown:
  auto_ids: false
